---
- name: Get the status of Minecraft Waterland resource pack install directory
  ansible.builtin.stat:
    path: "{{ mcw_resource_pack_install_dir }}"
  register: minecraft_waterland_resource_pack_install_dir

- name: Fail if Minecraft Waterland resource pack install dir does not exist
  ansible.builtin.fail:
    msg: "Unable to resume provisioning because {{ minecraft_waterland_resource_pack_install_dir }} does not exist"
  when: not minecraft_waterland_resource_pack_install_dir.stat.exists

- name: Create a temporary directory for storing downloaded files
  ansible.builtin.tempfile:
    state: directory
    suffix: mcw-tmp
  register: mcw_temp_dir_info

- name: Display the path to the temporary directory
  ansible.builtin.debug:
    var: mcw_temp_dir_info.path

- name: Download Minecraft Waterland resource pack file
  ansible.builtin.get_url:
    url: "{{ minecraft_waterland_versions[mcw_version].resource_packs['url'] }}"
    dest: "{{ mcw_temp_dir_info.path }}/resource-pack-{{ mcw_version }}.zip"
    mode: 0644

- name: Get the status of downloaded Minecraft Waterland resource pack file
  ansible.builtin.stat:
    path: "{{ mcw_temp_dir_info.path }}/resource-pack-{{ mcw_version }}.zip"
    checksum_algorithm: sha256
  register: minecraft_waterland_resource_pack_file

- name: Fail if downloaded Minecraft Waterland resource pack file checksum does not match
  ansible.builtin.fail:
    msg: "Downloaded Minecraft Waterland resource pack file checksum {{ minecraft_waterland_resource_pack_file.stat.checksum }} does not match the expected checksum {{ minecraft_waterland_versions[mcw_version].resource_pack.sha256 }}"
  when: not minecraft_waterland_resource_pack_file.stat.exists and minecraft_waterland_resource_pack_file.stat.checksum != minecraft_waterland_versions[mcw_version].resource_pack.sha256

- name: Unarchive Minecraft Waterland resource pack file to install dir
  ansible.builtin.unarchive:
    src: "{{ mcw_temp_dir_info.path }}/resource-pack-{{ mcw_version }}.zip"
    dest: "{{ mcw_resource_pack_install_dir }}"
    remote_src: true
